name: Maven CI
run-name: Deploy to ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
      - dev
jobs:
  compilation_et_test:
    name: Compilation et tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64